### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by pllk** [pllk/cphb#19]
Syntax highlighting in code examples would be nice

**Comment by yuizy** [comment]
[ShareLatex - Syntax highlighting draft](https://www.sharelatex.com/project/58c2877cfb616ab562441603)  (press Recompile if needed)

The default font looked a bit off so I used **inconsolata**. I also copied the colors from a randomly selected popular atom light theme. I have poor eye for color design. Feel free to modify.

**Comment by pllk** [comment]
@yuizy this looks very good, thank you!
