### ISSUE TITLE
Z-algorithm implementation

### ISSUE THREAD

**Issue by yuizy** [pllk/cphb#20]
The implementation for Z-algorithm is rather interesting since I believe the so called textbook implementation involves a lot of branches and potential one-off errors. Here's a rather short implementation that could be included in the book, similar to Manacher's algorithm. The key observation is that the while-loop will fail on the first iteration whenever we are strictly inside a longer match.

 Any ideas on how to make it even simpler?

```
int l = 0, r = 0;
for(int i = 1; i < s.size(); i++) {
     // if i inside current rightmost match (l..r), 
     //   set z[i] to match "shadow" position (i-l) but capped at r-i+1
    if(i <= r) z[i] = min(r - i + 1, z[i - l]);

    // increase z[i] until mismatch or end
    while(z[i] + i < s.size() && s[z[i]] == s[i + z[i]]) z[i]++; 

    // update current rightmost match
    if(i + z[i] - 1 > r) {
         l = i;
         r = i + z[i] - 1;
     }
}
```
[Implementation and some test cases on ideone.com](http://ideone.com/JZuyGf) in case you want to fork and try improving this one.

**Comment by pllk** [comment]
Your implementation is quite similar to this:
https://github.com/Laakeri/contestlib/blob/master/src/string/z.cpp

Still, I'm not sure whether it's a good idea to include an implementation in the book, or should the reader try to understand and implement the algorithm?

**Comment by yuizy** [comment]
That is a good question, and should be up to you as the author. I noticed that some of the chapters in the book do have sample implementations and some don't, so I don't know where the line should be (or is) drawn. I do remember though that back when I was studying I initially struggled with writing Z-algorithm the "long way" (which is taught in quite a few online tutorials) and it made the algorithm seem relatively complex and tricky to implement. Coming up with a concise implementation made the algorithm look much simpler and understandable, and to have less room for errors. 

I personally think it would make the chapter "easier" for the reader, but I guess this is more of a philosophical question about the goals of the book - and the question that if we add this implementation, do we need to add one for each chapter.

Feel free to close the issue if you feel like it's up to the reader to come up with the implementation.

As a sidenote, I'd also suggest adding a README.MD  this repository at some point in the future with a contribution guide and perhaps notes about your plans and vision for the book. For example a lot of people in the Codeforces thread asked about having tasks related to each chapter, so a readme could be a good place to make those kinds of questions clear.

**Comment by pllk** [comment]
Currently the book contains implementations for some algorithms when there is a short and clever implementation that may be difficult to come up with. Indeed, the short implementation of the Z-algorithm could also be one such implementation.

It is good to keep this issue open and decide later what to do.
