### ISSUE TITLE
Dijsktra algorithm - priority queue

### ISSUE THREAD

**Issue by Linkus000** [pllk/cphb#41]
In your dijkstra algorithm you suggest using negative distances, as a workaround for priority_queue sorting by the maximum element by default.

I think, a better solution would be to use std::greater as a template argument.

`priority_queue<pair<int,int>, vector<pair<int,int>>, greater<pair<int,int>>> q;`

**Comment by pllk** [comment]
I have considered this and in my opinion, it's still a better way in competitive programming to use negative distances.

**Comment by Linkus000** [comment]
Why is it?

**Comment by pllk** [comment]
Because in this case you only have to write 1-2 minus signs instead of the complicated maximum priority queue declaration.
