### ISSUE TITLE
Birthday paradox

### ISSUE THREAD

**Issue by darbula** [pllk/cphb#54]
Shouldn't this [line](https://github.com/pllk/cphb/blob/master/chapter26.tex#L405) be using term large instead of small?

> The phenomenon in scenario 3 is known as the birthday paradox: if there are n people in a room, the probability that some two people have the same birthday is large even if n is quite small.

**Comment by pllk** [comment]
I think the current form is correct, because the point is that even if there are not many people, the probability that some two people have the same birthday is large. Or could you clarify if I misunderstood your comment?

**Comment by darbula** [comment]
The point stated in your comment and in the book is correct but phrasing is misleading:

> even if there are *not many* people, the probability that some two people have the same birthday is large

If there are not many people (n is small) then it is obvious that the probability is large, but word 'even' suggests that you want to state something that is not obvious. The fact that indeed is not obvious is that if the n is large then the probability is larger than the probability uninformed reader would have estimated.
