### ISSUE TITLE
Bellman-Ford example

### ISSUE THREAD

**Issue by pllk** [pllk/cphb#60]
The example graph actually has a negative "cycle" between nodes 3 and 4. This should be fixed.

**Comment by darbula** [comment]
Since now the example has no negative weight edges maybe it would be more appropriate to switch to directed graph. Also the example in the subsection Negative cycles has shorter negative cycle between nodes 3 and 4.

**Comment by 1612198** [comment]
I have just found out it and i'm here. :'( I took me an hour to get dumb.

**Comment by 1612198** [comment]
> Since now the example has no negative weight edges maybe it would be more appropriate to switch to directed graph. Also the example in the subsection Negative cycles has shorter negative cycle between nodes 3 and 4.

I think it will be more clear when you give a directed graph in example section.
