### ISSUE TITLE
Updated pdf

### ISSUE THREAD

**Issue by wilfreddesert** [pllk/cphb#71]
Hi!

First of all, thank you so much for your priceless work. It seems that there have been some corrections since you last uploaded the pdf version of the book. Can you please update the pdf file. Being a perfectionist, I want to make sure I am using the most relevant version. I would do this myself, but I am experiencing some strange issue with MikTeX. Thank you!

**Comment by pllk** [comment]
Thank you! I have updated the PDF file now. It seems that there was one correction that was not included in the previous version.

**Comment by wilfreddesert** [comment]
Thank you very much! :) When I was trying to compile the book, the formatting turned out to be terrible
