### ISSUE TITLE
Is this book available in print?

### ISSUE THREAD

**Issue by olav35** [pllk/cphb#75]
Hello

Is this book available in print? I understand that there is a similar book called Guide to Competitive Programming that is based on this one. Is that book aimed at the same audience? 

I'm apologize if this is the wrong place to ask.

Olav

**Comment by pllk** [comment]
Yes, Guide to Competitive Programming is the printed version of the book. Both the books have the same origins but the printed book has some additional topics.

**Comment by olav35** [comment]
Alright. Thank you.

Closing.
